// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\Jluce\Desktop\задачки\geo\app-1\internal\interfaces\http\services\repositories.go
//
// Generated by this command:
//
//	mockgen -source=C:\Users\Jluce\Desktop\задачки\geo\app-1\internal\interfaces\http\services\repositories.go -destination=mocks/service_mock .go -package=mocks
//

// Package mock_services is a generated GoMock package.
package mock_services

import (
	context "context"
	reflect "reflect"
	time "time"

	dto "github.com/BitCoinOffical/geo-announcements/app-1/internal/interfaces/http/dto"
	models "github.com/BitCoinOffical/geo-announcements/app-1/internal/interfaces/http/models"
	gomock "go.uber.org/mock/gomock"
)

// MockincidentRepository is a mock of incidentRepository interface.
type MockincidentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockincidentRepositoryMockRecorder
	isgomock struct{}
}

// MockincidentRepositoryMockRecorder is the mock recorder for MockincidentRepository.
type MockincidentRepositoryMockRecorder struct {
	mock *MockincidentRepository
}

// NewMockincidentRepository creates a new mock instance.
func NewMockincidentRepository(ctrl *gomock.Controller) *MockincidentRepository {
	mock := &MockincidentRepository{ctrl: ctrl}
	mock.recorder = &MockincidentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockincidentRepository) EXPECT() *MockincidentRepositoryMockRecorder {
	return m.recorder
}

// CreateIncidents mocks base method.
func (m *MockincidentRepository) CreateIncidents(ctx context.Context, arg1 *dto.IncidentDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIncidents", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateIncidents indicates an expected call of CreateIncidents.
func (mr *MockincidentRepositoryMockRecorder) CreateIncidents(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIncidents", reflect.TypeOf((*MockincidentRepository)(nil).CreateIncidents), ctx, arg1)
}

// DeleteIncidentsByID mocks base method.
func (m *MockincidentRepository) DeleteIncidentsByID(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIncidentsByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIncidentsByID indicates an expected call of DeleteIncidentsByID.
func (mr *MockincidentRepositoryMockRecorder) DeleteIncidentsByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIncidentsByID", reflect.TypeOf((*MockincidentRepository)(nil).DeleteIncidentsByID), ctx, id)
}

// GetIncidentByID mocks base method.
func (m *MockincidentRepository) GetIncidentByID(ctx context.Context, id int) (*models.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncidentByID", ctx, id)
	ret0, _ := ret[0].(*models.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncidentByID indicates an expected call of GetIncidentByID.
func (mr *MockincidentRepositoryMockRecorder) GetIncidentByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncidentByID", reflect.TypeOf((*MockincidentRepository)(nil).GetIncidentByID), ctx, id)
}

// GetIncidentStat mocks base method.
func (m *MockincidentRepository) GetIncidentStat(ctx context.Context, fromTime *time.Time) (*models.UsersInDangerousZones, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncidentStat", ctx, fromTime)
	ret0, _ := ret[0].(*models.UsersInDangerousZones)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncidentStat indicates an expected call of GetIncidentStat.
func (mr *MockincidentRepositoryMockRecorder) GetIncidentStat(ctx, fromTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncidentStat", reflect.TypeOf((*MockincidentRepository)(nil).GetIncidentStat), ctx, fromTime)
}

// GetIncidents mocks base method.
func (m *MockincidentRepository) GetIncidents(ctx context.Context, page, limit int) ([]models.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncidents", ctx, page, limit)
	ret0, _ := ret[0].([]models.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncidents indicates an expected call of GetIncidents.
func (mr *MockincidentRepositoryMockRecorder) GetIncidents(ctx, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncidents", reflect.TypeOf((*MockincidentRepository)(nil).GetIncidents), ctx, page, limit)
}

// GetTop mocks base method.
func (m *MockincidentRepository) GetTop(ctx context.Context, limit int) ([]models.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTop", ctx, limit)
	ret0, _ := ret[0].([]models.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTop indicates an expected call of GetTop.
func (mr *MockincidentRepositoryMockRecorder) GetTop(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTop", reflect.TypeOf((*MockincidentRepository)(nil).GetTop), ctx, limit)
}

// UpdateIncidentsByID mocks base method.
func (m *MockincidentRepository) UpdateIncidentsByID(ctx context.Context, arg1 *dto.IncidentDTO, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIncidentsByID", ctx, arg1, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateIncidentsByID indicates an expected call of UpdateIncidentsByID.
func (mr *MockincidentRepositoryMockRecorder) UpdateIncidentsByID(ctx, arg1, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIncidentsByID", reflect.TypeOf((*MockincidentRepository)(nil).UpdateIncidentsByID), ctx, arg1, id)
}

// UpdateZones mocks base method.
func (m *MockincidentRepository) UpdateZones(ctx context.Context, arg1 *dto.IncidentDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateZones", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateZones indicates an expected call of UpdateZones.
func (mr *MockincidentRepositoryMockRecorder) UpdateZones(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateZones", reflect.TypeOf((*MockincidentRepository)(nil).UpdateZones), ctx, arg1)
}

// MockincidentCache is a mock of incidentCache interface.
type MockincidentCache struct {
	ctrl     *gomock.Controller
	recorder *MockincidentCacheMockRecorder
	isgomock struct{}
}

// MockincidentCacheMockRecorder is the mock recorder for MockincidentCache.
type MockincidentCacheMockRecorder struct {
	mock *MockincidentCache
}

// NewMockincidentCache creates a new mock instance.
func NewMockincidentCache(ctrl *gomock.Controller) *MockincidentCache {
	mock := &MockincidentCache{ctrl: ctrl}
	mock.recorder = &MockincidentCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockincidentCache) EXPECT() *MockincidentCacheMockRecorder {
	return m.recorder
}

// Del mocks base method.
func (m *MockincidentCache) Del(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Del", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Del indicates an expected call of Del.
func (mr *MockincidentCacheMockRecorder) Del(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*MockincidentCache)(nil).Del), ctx, id)
}

// Get mocks base method.
func (m *MockincidentCache) Get(ctx context.Context, id int) (*models.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*models.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockincidentCacheMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockincidentCache)(nil).Get), ctx, id)
}

// GetAll mocks base method.
func (m *MockincidentCache) GetAll(ctx context.Context, page, limit int) ([]models.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, page, limit)
	ret0, _ := ret[0].([]models.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockincidentCacheMockRecorder) GetAll(ctx, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockincidentCache)(nil).GetAll), ctx, page, limit)
}

// GetTop mocks base method.
func (m *MockincidentCache) GetTop(ctx context.Context) ([]models.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTop", ctx)
	ret0, _ := ret[0].([]models.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTop indicates an expected call of GetTop.
func (mr *MockincidentCacheMockRecorder) GetTop(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTop", reflect.TypeOf((*MockincidentCache)(nil).GetTop), ctx)
}

// Set mocks base method.
func (m *MockincidentCache) Set(ctx context.Context, key string, value any, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockincidentCacheMockRecorder) Set(ctx, key, value, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockincidentCache)(nil).Set), ctx, key, value, ttl)
}

// SetTop mocks base method.
func (m *MockincidentCache) SetTop(ctx context.Context, value any, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTop", ctx, value, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTop indicates an expected call of SetTop.
func (mr *MockincidentCacheMockRecorder) SetTop(ctx, value, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTop", reflect.TypeOf((*MockincidentCache)(nil).SetTop), ctx, value, ttl)
}

// MocklocationRepository is a mock of locationRepository interface.
type MocklocationRepository struct {
	ctrl     *gomock.Controller
	recorder *MocklocationRepositoryMockRecorder
	isgomock struct{}
}

// MocklocationRepositoryMockRecorder is the mock recorder for MocklocationRepository.
type MocklocationRepositoryMockRecorder struct {
	mock *MocklocationRepository
}

// NewMocklocationRepository creates a new mock instance.
func NewMocklocationRepository(ctrl *gomock.Controller) *MocklocationRepository {
	mock := &MocklocationRepository{ctrl: ctrl}
	mock.recorder = &MocklocationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocklocationRepository) EXPECT() *MocklocationRepositoryMockRecorder {
	return m.recorder
}

// CreateLocation mocks base method.
func (m *MocklocationRepository) CreateLocation(ctx context.Context, arg1 *dto.LocationDTO, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLocation", ctx, arg1, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLocation indicates an expected call of CreateLocation.
func (mr *MocklocationRepositoryMockRecorder) CreateLocation(ctx, arg1, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLocation", reflect.TypeOf((*MocklocationRepository)(nil).CreateLocation), ctx, arg1, userID)
}

// GetDangerZones mocks base method.
func (m *MocklocationRepository) GetDangerZones(ctx context.Context, arg1 *dto.LocationDTO, userID string) ([]models.DangerousZones, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDangerZones", ctx, arg1, userID)
	ret0, _ := ret[0].([]models.DangerousZones)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDangerZones indicates an expected call of GetDangerZones.
func (mr *MocklocationRepositoryMockRecorder) GetDangerZones(ctx, arg1, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDangerZones", reflect.TypeOf((*MocklocationRepository)(nil).GetDangerZones), ctx, arg1, userID)
}
