// Code generated by MockGen. DO NOT EDIT.
// Source: C:/Users/Jluce/Desktop/задачки/geo/app-1/internal/api/handlers/services.go
//
// Generated by this command:
//
//	mockgen -source=C:/Users/Jluce/Desktop/задачки/geo/app-1/internal/api/handlers/services.go -destination=mocks/handlers_mock .go -package=mocks
//

// Package mock_handlers is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	config "github.com/BitCoinOffical/geo-announcements/app-1/config"
	dto "github.com/BitCoinOffical/geo-announcements/app-1/internal/interfaces/http/dto"
	models "github.com/BitCoinOffical/geo-announcements/app-1/internal/interfaces/http/models"
	gomock "go.uber.org/mock/gomock"
)

// MockincidentService is a mock of incidentService interface.
type MockincidentService struct {
	ctrl     *gomock.Controller
	recorder *MockincidentServiceMockRecorder
	isgomock struct{}
}

// MockincidentServiceMockRecorder is the mock recorder for MockincidentService.
type MockincidentServiceMockRecorder struct {
	mock *MockincidentService
}

// NewMockincidentService creates a new mock instance.
func NewMockincidentService(ctrl *gomock.Controller) *MockincidentService {
	mock := &MockincidentService{ctrl: ctrl}
	mock.recorder = &MockincidentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockincidentService) EXPECT() *MockincidentServiceMockRecorder {
	return m.recorder
}

// CreateIncidents mocks base method.
func (m *MockincidentService) CreateIncidents(ctx context.Context, arg1 *dto.IncidentDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIncidents", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateIncidents indicates an expected call of CreateIncidents.
func (mr *MockincidentServiceMockRecorder) CreateIncidents(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIncidents", reflect.TypeOf((*MockincidentService)(nil).CreateIncidents), ctx, arg1)
}

// DeleteIncidentsByID mocks base method.
func (m *MockincidentService) DeleteIncidentsByID(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIncidentsByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIncidentsByID indicates an expected call of DeleteIncidentsByID.
func (mr *MockincidentServiceMockRecorder) DeleteIncidentsByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIncidentsByID", reflect.TypeOf((*MockincidentService)(nil).DeleteIncidentsByID), ctx, id)
}

// GetIncidentByID mocks base method.
func (m *MockincidentService) GetIncidentByID(ctx context.Context, id int) (*models.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncidentByID", ctx, id)
	ret0, _ := ret[0].(*models.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncidentByID indicates an expected call of GetIncidentByID.
func (mr *MockincidentServiceMockRecorder) GetIncidentByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncidentByID", reflect.TypeOf((*MockincidentService)(nil).GetIncidentByID), ctx, id)
}

// GetIncidentStat mocks base method.
func (m *MockincidentService) GetIncidentStat(ctx context.Context, cfg *config.AppConfig) (*models.UsersInDangerousZones, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncidentStat", ctx, cfg)
	ret0, _ := ret[0].(*models.UsersInDangerousZones)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncidentStat indicates an expected call of GetIncidentStat.
func (mr *MockincidentServiceMockRecorder) GetIncidentStat(ctx, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncidentStat", reflect.TypeOf((*MockincidentService)(nil).GetIncidentStat), ctx, cfg)
}

// GetIncidents mocks base method.
func (m *MockincidentService) GetIncidents(ctx context.Context, page, limit int) ([]models.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncidents", ctx, page, limit)
	ret0, _ := ret[0].([]models.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncidents indicates an expected call of GetIncidents.
func (mr *MockincidentServiceMockRecorder) GetIncidents(ctx, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncidents", reflect.TypeOf((*MockincidentService)(nil).GetIncidents), ctx, page, limit)
}

// UpdateIncidentsByID mocks base method.
func (m *MockincidentService) UpdateIncidentsByID(ctx context.Context, arg1 *dto.IncidentDTO, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIncidentsByID", ctx, arg1, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateIncidentsByID indicates an expected call of UpdateIncidentsByID.
func (mr *MockincidentServiceMockRecorder) UpdateIncidentsByID(ctx, arg1, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIncidentsByID", reflect.TypeOf((*MockincidentService)(nil).UpdateIncidentsByID), ctx, arg1, id)
}

// MocklocationService is a mock of locationService interface.
type MocklocationService struct {
	ctrl     *gomock.Controller
	recorder *MocklocationServiceMockRecorder
	isgomock struct{}
}

// MocklocationServiceMockRecorder is the mock recorder for MocklocationService.
type MocklocationServiceMockRecorder struct {
	mock *MocklocationService
}

// NewMocklocationService creates a new mock instance.
func NewMocklocationService(ctrl *gomock.Controller) *MocklocationService {
	mock := &MocklocationService{ctrl: ctrl}
	mock.recorder = &MocklocationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocklocationService) EXPECT() *MocklocationServiceMockRecorder {
	return m.recorder
}

// CreateLocation mocks base method.
func (m *MocklocationService) CreateLocation(ctx context.Context, arg1 *dto.LocationDTO, userID string) ([]models.DangerousZones, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLocation", ctx, arg1, userID)
	ret0, _ := ret[0].([]models.DangerousZones)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLocation indicates an expected call of CreateLocation.
func (mr *MocklocationServiceMockRecorder) CreateLocation(ctx, arg1, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLocation", reflect.TypeOf((*MocklocationService)(nil).CreateLocation), ctx, arg1, userID)
}
