// Code generated by MockGen. DO NOT EDIT.
// Source: C:/Users/Jluce/Desktop/задачки/geo/app-1/internal/api/handlers/services.go
//
// Generated by this command:
//
//	mockgen -source=C:/Users/Jluce/Desktop/задачки/geo/app-1/internal/api/handlers/services.go -destination=mocks/handlers_mock .go -package=mocks
//

// Package mock_handlers is a generated GoMock package.
package mock_handlers

import (
	context "context"
	reflect "reflect"

	dto "github.com/BitCoinOffical/geo-announcements/app-1/internal/interfaces/http/dto"
	models "github.com/BitCoinOffical/geo-announcements/app-1/internal/interfaces/http/models"
	redis "github.com/redis/go-redis/v9"
	gomock "go.uber.org/mock/gomock"
)

// MockincidentService is a mock of incidentService interface.
type MockincidentService struct {
	ctrl     *gomock.Controller
	recorder *MockincidentServiceMockRecorder
	isgomock struct{}
}

// MockincidentServiceMockRecorder is the mock recorder for MockincidentService.
type MockincidentServiceMockRecorder struct {
	mock *MockincidentService
}

// NewMockincidentService creates a new mock instance.
func NewMockincidentService(ctrl *gomock.Controller) *MockincidentService {
	mock := &MockincidentService{ctrl: ctrl}
	mock.recorder = &MockincidentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockincidentService) EXPECT() *MockincidentServiceMockRecorder {
	return m.recorder
}

// CreateIncidents mocks base method.
func (m *MockincidentService) CreateIncidents(ctx context.Context, arg1 *dto.IncidentDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIncidents", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateIncidents indicates an expected call of CreateIncidents.
func (mr *MockincidentServiceMockRecorder) CreateIncidents(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIncidents", reflect.TypeOf((*MockincidentService)(nil).CreateIncidents), ctx, arg1)
}

// DeleteIncidentsByID mocks base method.
func (m *MockincidentService) DeleteIncidentsByID(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIncidentsByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIncidentsByID indicates an expected call of DeleteIncidentsByID.
func (mr *MockincidentServiceMockRecorder) DeleteIncidentsByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIncidentsByID", reflect.TypeOf((*MockincidentService)(nil).DeleteIncidentsByID), ctx, id)
}

// GetIncidentByID mocks base method.
func (m *MockincidentService) GetIncidentByID(ctx context.Context, id int) (*models.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncidentByID", ctx, id)
	ret0, _ := ret[0].(*models.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncidentByID indicates an expected call of GetIncidentByID.
func (mr *MockincidentServiceMockRecorder) GetIncidentByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncidentByID", reflect.TypeOf((*MockincidentService)(nil).GetIncidentByID), ctx, id)
}

// GetIncidentStat mocks base method.
func (m *MockincidentService) GetIncidentStat(ctx context.Context, StatsTimeWindowMinutes int) (*models.UsersInDangerousZones, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncidentStat", ctx, StatsTimeWindowMinutes)
	ret0, _ := ret[0].(*models.UsersInDangerousZones)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncidentStat indicates an expected call of GetIncidentStat.
func (mr *MockincidentServiceMockRecorder) GetIncidentStat(ctx, StatsTimeWindowMinutes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncidentStat", reflect.TypeOf((*MockincidentService)(nil).GetIncidentStat), ctx, StatsTimeWindowMinutes)
}

// GetIncidents mocks base method.
func (m *MockincidentService) GetIncidents(ctx context.Context, page, limit int) ([]models.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncidents", ctx, page, limit)
	ret0, _ := ret[0].([]models.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncidents indicates an expected call of GetIncidents.
func (mr *MockincidentServiceMockRecorder) GetIncidents(ctx, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncidents", reflect.TypeOf((*MockincidentService)(nil).GetIncidents), ctx, page, limit)
}

// UpdateIncidentsByID mocks base method.
func (m *MockincidentService) UpdateIncidentsByID(ctx context.Context, arg1 *dto.IncidentDTO, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIncidentsByID", ctx, arg1, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateIncidentsByID indicates an expected call of UpdateIncidentsByID.
func (mr *MockincidentServiceMockRecorder) UpdateIncidentsByID(ctx, arg1, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIncidentsByID", reflect.TypeOf((*MockincidentService)(nil).UpdateIncidentsByID), ctx, arg1, id)
}

// UpdateZones mocks base method.
func (m *MockincidentService) UpdateZones(ctx context.Context, arg1 *dto.IncidentDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateZones", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateZones indicates an expected call of UpdateZones.
func (mr *MockincidentServiceMockRecorder) UpdateZones(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateZones", reflect.TypeOf((*MockincidentService)(nil).UpdateZones), ctx, arg1)
}

// MocklocationService is a mock of locationService interface.
type MocklocationService struct {
	ctrl     *gomock.Controller
	recorder *MocklocationServiceMockRecorder
	isgomock struct{}
}

// MocklocationServiceMockRecorder is the mock recorder for MocklocationService.
type MocklocationServiceMockRecorder struct {
	mock *MocklocationService
}

// NewMocklocationService creates a new mock instance.
func NewMocklocationService(ctrl *gomock.Controller) *MocklocationService {
	mock := &MocklocationService{ctrl: ctrl}
	mock.recorder = &MocklocationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocklocationService) EXPECT() *MocklocationServiceMockRecorder {
	return m.recorder
}

// CreateLocation mocks base method.
func (m *MocklocationService) CreateLocation(ctx context.Context, arg1 *dto.LocationDTO, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLocation", ctx, arg1, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLocation indicates an expected call of CreateLocation.
func (mr *MocklocationServiceMockRecorder) CreateLocation(ctx, arg1, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLocation", reflect.TypeOf((*MocklocationService)(nil).CreateLocation), ctx, arg1, userID)
}

// GetDangerZones mocks base method.
func (m *MocklocationService) GetDangerZones(ctx context.Context, arg1 *dto.LocationDTO) ([]models.DangerousZones, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDangerZones", ctx, arg1)
	ret0, _ := ret[0].([]models.DangerousZones)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDangerZones indicates an expected call of GetDangerZones.
func (mr *MocklocationServiceMockRecorder) GetDangerZones(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDangerZones", reflect.TypeOf((*MocklocationService)(nil).GetDangerZones), ctx, arg1)
}

// MockwebhookRetry is a mock of webhookRetry interface.
type MockwebhookRetry struct {
	ctrl     *gomock.Controller
	recorder *MockwebhookRetryMockRecorder
	isgomock struct{}
}

// MockwebhookRetryMockRecorder is the mock recorder for MockwebhookRetry.
type MockwebhookRetryMockRecorder struct {
	mock *MockwebhookRetry
}

// NewMockwebhookRetry creates a new mock instance.
func NewMockwebhookRetry(ctrl *gomock.Controller) *MockwebhookRetry {
	mock := &MockwebhookRetry{ctrl: ctrl}
	mock.recorder = &MockwebhookRetryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockwebhookRetry) EXPECT() *MockwebhookRetryMockRecorder {
	return m.recorder
}

// Retry mocks base method.
func (m *MockwebhookRetry) Retry(ctx context.Context, webhook *dto.WebHookDTO) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Retry", ctx, webhook)
}

// Retry indicates an expected call of Retry.
func (mr *MockwebhookRetryMockRecorder) Retry(ctx, webhook any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Retry", reflect.TypeOf((*MockwebhookRetry)(nil).Retry), ctx, webhook)
}

// MockDBPinger is a mock of DBPinger interface.
type MockDBPinger struct {
	ctrl     *gomock.Controller
	recorder *MockDBPingerMockRecorder
	isgomock struct{}
}

// MockDBPingerMockRecorder is the mock recorder for MockDBPinger.
type MockDBPingerMockRecorder struct {
	mock *MockDBPinger
}

// NewMockDBPinger creates a new mock instance.
func NewMockDBPinger(ctrl *gomock.Controller) *MockDBPinger {
	mock := &MockDBPinger{ctrl: ctrl}
	mock.recorder = &MockDBPingerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBPinger) EXPECT() *MockDBPingerMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockDBPinger) Ping() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping")
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockDBPingerMockRecorder) Ping() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockDBPinger)(nil).Ping))
}

// MockRedisPinger is a mock of RedisPinger interface.
type MockRedisPinger struct {
	ctrl     *gomock.Controller
	recorder *MockRedisPingerMockRecorder
	isgomock struct{}
}

// MockRedisPingerMockRecorder is the mock recorder for MockRedisPinger.
type MockRedisPingerMockRecorder struct {
	mock *MockRedisPinger
}

// NewMockRedisPinger creates a new mock instance.
func NewMockRedisPinger(ctrl *gomock.Controller) *MockRedisPinger {
	mock := &MockRedisPinger{ctrl: ctrl}
	mock.recorder = &MockRedisPingerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedisPinger) EXPECT() *MockRedisPingerMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockRedisPinger) Ping(ctx context.Context) *redis.StatusCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(*redis.StatusCmd)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockRedisPingerMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockRedisPinger)(nil).Ping), ctx)
}
