CREATE DATABASE IF NOT EXISTS geodb;

CREATE TABLE IF NOT EXISTS incidents (
	incident_id SERIAL PRIMARY KEY,
	lat VARCHAR(16),
	lon VARCHAR(16),
	create_at TIMESTAMP DEFAULT NOW(),
	update_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS locations (
	location_id SERIAL PRIMARY KEY,
	user_id UUID NOT NULL,
	lat VARCHAR(16),
	lon VARCHAR(16),
	create_at   TIMESTAMP DEFAULT NOW()
);